name: tiny_storage
description: This is a simple key-value store based on JSON file.
version: 1.0.0
homepage: https://github.com/zuvola/tiny_storage

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  isoworker: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
