name: tiny_storage
description: This is a simple key-value store based on JSON file. Parallel processing of file I/O using `Isolate`.
version: 1.0.1
homepage: https://github.com/zuvola/tiny_storage

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  isoworker: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.12
