name: tiny_storage
description: This is a simple key-value store based on JSON file. Parallel processing of file I/O using `Isolate`.
version: 1.1.0
homepage: https://github.com/zuvola/tiny_storage

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  isoworker: ^1.1.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.25.2
