name: tiny_storage
description: A simple and lightweight key-value store that saves data as JSON files. Supports fast and ordered file I/O using Isolate-based parallel processing.
version: 2.0.0
homepage: https://github.com/zuvola/tiny_storage

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  isoworker: ^2.0.0
  meta: ^1.17.0
  web: ^1.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.1
